source 'https://rubygems.org'
gem 'discordrb', git: 'https://github.com/shardlab/discordrb.git'
gem 'airrecord'
gem 'themoviedb'
gem 'myanimelist_client'
gem 'googlebooks'
gem 'rspec'
gem 'config'
gem 'tzinfo'
gem 'pry'
gem 'igdb_client', git: 'https://github.com/darkstego/igdb_client.git'
