source 'https://rubygems.org'
gem 'discordrb', '3.4.2',git: 'https://github.com/shardlab/discordrb.git'
gem 'airrecord'
gem 'themoviedb'
gem 'igdb_client'
gem 'myanimelist_client'
gem 'googlebooks'
gem 'rspec'
gem 'config'
gem 'tzinfo'
gem 'pry'
